{
  TetzkatLipHoka 2015-2018

  uTLH: Include
  Last updated: 28.01.2016
}

{.$DEFINE INDY90}        // used INDY Version
{$DEFINE INDY100}

// uTLH.Math
{.$DEFINE MATHROUT}      // ePunkt and descendants

// uTLH.SysUtils
{$DEFINE SetTimePeriod} // Auto Synchronize TimePeriods on Initialize

// uTLH.Graphics
{$DEFINE usePNGLib}     // Kyouzou (Native in XE)
{$DEFINE useTIFLib}     // Kyouzou (Bypassed since XE)
{.$DEFINE GR32}          // Graphics32 (CanvasClone & BitmapResize)





